<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository {

    /**
     * @return mixed
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFirstRoom() {
        $qb = $this->createQueryBuilder('room')
            ->where('room.previousRoom IS NULL');

        return $qb->getQuery()->getSingleResult();
    }
}
